### PR TITLE
Update README.md with flake example

### PR DESCRIPTION
**Pull request by BeardedTek**
Update README.md to include example of addition to flakes. It took me an hour of looking this up and failing until I found this information on reddit:

https://www.reddit.com/r/NixOS/comments/16ofx87/plasma_6/

### CODE REVIEW

**Comment by K900** [comment]
Can you squash the commits please? And also preferably update the commit message to explain what you actually changed.

**Comment by BeardedTek** [comment]
I'll get to this tonight.  It's been a busy Monday :(

**Comment by BeardedTek** [comment]
Okay, I honestly don't know if I did this right.  I'm used to working on my own git repos, not contributing to others.

**Comment by K900** [comment]
Mostly yes, but I'm sorry, but I'll probably shut this repo down soon in favor of the Nixpkgs PR, as that got some pretty invasive changes.

**Comment by BeardedTek** [comment]
If nothing else I learned something new.  Thanks for all the hard work!!!

**Pull request closed without merging**
